jira:
  url: "https://scylladb.atlassian.net"

jira_project: "DRIVER"
github_title_strip:
  - '^\[.*?\]\s*'
default_worktype: "Task"
type_mapping:
  Epic: "Epic"

repos:
  # Drivers
  - github: "scylladb/python-driver"
    jira_prefix: "python-driver:"
    scylla_components: "Driver - python-driver"
  - github: "scylladb/java-driver"
    github_title_strip: '^[43]\\.[xX]:\s*'
    rules:
      - match:
          issue_title: "^3\\.[xX]:"
        jira_prefix: "java-driver-3.x:"
        scylla_components: "Driver - java-driver-3.x"
      - match:
          issue_title: "^4\\.[xX]:"
        jira_prefix: "java-driver-4.x:"
        scylla_components: "Driver - java-driver-4.x"
    jira_prefix: "java-driver:"
    scylla_components: "Driver - java-driver-4.x"
  - github: "scylladb/nodejs-rs-driver"
    jira_prefix: "nodejs-rs-driver:"
    scylla_components: "Driver - nodejs-rs-driver"
  - github: "scylladb/scylla-rust-driver"
    jira_prefix: "rust-driver:"
    scylla_components: "Driver - rust-driver"
  - github: "scylladb/gocql"
    jira_prefix: "gocql:"
    scylla_components: "Driver - gocql"
  - github: "scylladb/gocqlx"
    jira_prefix: "gocqlx:"
    scylla_components: "gocqlx"
  - github: "scylladb/csharp-driver"
    jira_prefix: "csharp-driver:"
    scylla_components: "Driver - csharp-driver"
  - github: "scylladb/cpp-rs-driver"
    jira_prefix: "cpp-rs-driver:"
    scylla_components: "Driver - cpp-rs-driver"

  # Alternator clients
  - github: "scylladb/alternator-client-java"
    jira_prefix: "alternator-client-java:"
    scylla_components: "Alternator Client - java"
  - github: "scylladb/alternator-client-golang"
    jira_prefix: "alternator-client-golang:"
    scylla_components: "Alternator Client - golang"
  - github: "scylladb/alternator-client-python"
    jira_prefix: "alternator-client-python:"
    scylla_components: "Alternator Client - python"
  - github: "scylladb/alternator-client-javascript"
    jira_prefix: "alternator-client-javascript:"
    scylla_components: "Alternator Client - javascript"
  - github: "scylladb/alternator-client-cpp"
    jira_prefix: "alternator-client-cpp:"
    scylla_components: "Alternator Client - cpp"
  - github: "scylladb/alternator-client-rust"
    jira_prefix: "alternator-client-rust:"
    scylla_components: "Alternator Client - rust"
  - github: "scylladb/alternator-client-csharp"
    jira_prefix: "alternator-client-csharp:"
    scylla_components: "Alternator Client - csharp"

  # Everything else
  - github: "scylladb/alternator-load-balancing"
    jira_prefix: "[Alternator Clients]:"
    scylla_components: "Alternator Clients"
  - github: "scylladb/scylla-cdc-source-connector"
    jira_prefix: "cdc-source-connector:"
    scylla_components: "Connector - cdc-source-connector"
  - github: "scylladb/scylla-migrator"
    jira_prefix: "scylla-migrator:"
    scylla_components: "scylla-migrator"
  - github: "scylladb/spark-scylladb-connector"
    jira_prefix: "spark-scylladb-connector:"
    scylla_components: "Connector - spark-connector"
  - github: "scylladb/scylla-drivers"
    jira_prefix: "[Scylla Drivers]:"
    scylla_components: "Drivers"

